branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: CGV Project
  branch: null
  default_ec2_keyname: wps-8th-rec
  default_platform: Docker 18.06.1-ce
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: Ryanden
  repository: null
  sc: null
  workspace_type: Application
